FROM python:3-slim

COPY requirements_http.txt /src/
RUN python3 -m pip install -r /src/requirements_http.txt

COPY telegraph_webhook.py /src/
WORKDIR /src/
EXPOSE 80
CMD ["gunicorn", "telegraph_webhook:app", "-b", "0.0.0.0:80"]