apiVersion: v1
kind: Namespace
metadata:
  name: telegraph
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp
  namespace: telegraph
  labels:
    app: smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp
  template:
    metadata:
      labels:
        app: smtp
    spec:
      containers:
      - name: smtp
        image: evilben/telegraph_smtp:(hash)
        env:
        - name: MQTT_SERVER
          value: mosquitto.mqtt
        ports:
        - containerPort: 25
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: smtp
  namespace: telegraph
  labels:
    app: smtp
spec:
  selector:
    app: smtp
  ports:
  - port: 25
    targetPort: 25
    protocol: TCP
    name: smtp
  externalIPs: ["172.30.2.4"]

